### PR TITLE
Create pt-BR translations

### PR DESCRIPTION
**Pull request by lucawen**

### CODE REVIEW

**Comment by Hanziness** [comment]
Thank you very much for submitting this, but language contributions are now handled in the [app's Crowdin project](https://crowdin.com/project/anotherpomodoro). If you can help me keep it updated there, I can upload your translations (so you won't have to retype anything) and then sync them in with the project :)

**Comment by lucawen** [comment]
Yes, this will be awesome! I can help make this updated over Crowdin. My username there is lucawen.

**Comment by Hanziness** [comment]
I have uploaded your translations to Crowdin, thank you very much for submitting them! I'll close this issue and enable the localizations manually very soon.

**Comment by Hanziness** [comment]
🎉 The translations are live with version [v1.4.3](https://github.com/Hanziness/FocusTide/releases/tag/v1.4.3), thank you very much for your help.

**Pull request closed without merging**
