### PR TITLE
i18n: Add Croatian translation

### PR DESCRIPTION
**Pull request by milotype**
- translation according to the newest english version "en.js" where some strings have been removed

### CODE REVIEW

**Comment by Hanziness** [comment]
Thank you! I'm continuing the discussion started in #149 here. So, no worries about not being a programmer, I'll add the required settings :)

**Comment by Hanziness** [comment]
Great! It's working! Thank you very much for your contribution! In the future, I'm considering moving translations out from files to a platform like Crowdin so people don't have to keep submitting PRs to add translations.

**Comment by milotype** [comment]
@Hanziness Whoops, Croatian is gone again on https://another-pomodoro.netlify.app/ !?

**Comment by Hanziness** [comment]
Yes, don't worry, it is supposed to *not* show up :) I accidentally published a preview version, which was live for a short time, that's what you have seen with the new UI and the translations. The 1.0 version (which will include Croatian) will probably release on Wednesday, when it will be published at the app's URL.

Developers can clone the repo's default branch (`develop`) and follow the instructions found at the bottom of the README to run the latest version locally (you need to install NodeJS and yarn to do that) :)

**Pull request merged**
