### PR TITLE
i18n: Croatian translation

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by Hanziness** [comment]
Thank you so much for your contribution! I'll test your PR and merge it as soon as I get there.

**Comment by Hanziness** [comment]
Can you please update your PR to the latest `develop`? I've made a few changes to let the app accept new languages easier (languages are a lot less hard-coded) and only a few small changes need to be followed:

* remove the modifications in `en.js` and `hu.js` around lines 233-240 (language names are not stored in each translation file anymore, the `settings.values.lang` key was deleted), the same lines can also be deleted from `hr.js`
* add an entry to [`nuxt.config.js`](https://github.com/Hanziness/AnotherPomodoro/blob/develop/nuxt.config.js#L134) into the `i18n.locales` array
* check if Croatian shows up on the settings panel and the setup page (`/setup`) and the app can be switched to it. Unfortunately, the default timer will likely not change languages because those translations are handled by day.js. I'll see if I can automate the loading of those translations in the future.

**Comment by milotype** [comment]
@Hanziness You can close this PR. 
I've updated the project on my side, generated a new branch and opened a new PR #155.

**Comment by milotype** [comment]
I'm not a programmer ... so in the new PR #155 I just did the necessary changes for the `hr.js` file.
I don't understand the other two points you mentioned in your answer. Sorry.

**Comment by milotype** [comment]
OK, point number three I can check once you update the app.
I'll then open https://another-pomodoro.netlify.app/ click **QUICKSTART** and will check if _Croatian_ appears in the settings.
But point two I simply don't undertand, sorry.

**Pull request closed without merging**
